version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development
      - SERVER_PORT=8000
      - CONNECTIONSTRING=mongodb://mongo:27017/psy
    volumes:
      - ./:/app

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
